BOARD_SIZE = 8
RECT_SIZE = 50
CIRCLE_OFFSET = 5
KING_OFFSET = 10
RECT_COLORS = ["grey", "red"]
CIRCLE_COLORS = ["white", "black"]
KING_COLOR = ["gold"]
CIRCLE_COLOR_SELECTED = "blue"
PLAYER_A = 0 # AI-Player
PLAYER_B = 1 # Human-Player